function sumator1(tip,tip1,R,R1,R2,A1,A2,F1,F2,N,Vo1,Vo2, DC1, DC2)

figure('Name','Proiect GAC',...
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.8],...
           'NumberTitle','off','color',[0.75,0.75,0.75]);
        f=uimenu('Label','Proiect');
           uimenu(f,'Label','Pagina de start','Callback','Start');  
           uimenu(f,'Label','Teorie','Callback','open(''Teorie.docx'')'); 
           uimenu(f,'Label','Iesire','Callback','close',...
                    'Separator','on','Accelerator','Q');
T1=1/F1;
T2=1/F2;
t1=0:T1/100:N*T1;
t2=0:T2/100:N*T2;

F=gcd(F1,F2);
T=1/F;
t=0:T/100:N*T;

uicontrol('Style','text',...
 'FontSize',20,...
 'Units','normalized',...
 'Position',[0.04 0.94 0.36 0.05],...
 'String','SUMATOR INVERSOR ');
ho = axes('units','normalized', ...
'position',[0.008 0.62 0.445 0.28]);
uistack(ho,'bottom');
V=imread('Inversor.jpg');
hp = imagesc(V);
colormap gray
set(ho,'handlevisibility','off', ...
'visible','off');
set(hp,'alphadata',1);

ha = axes('units','normalized', ...
'position',[0 0 1 1]);
uistack(ha,'bottom');
I=imread('im2.png');
hi = imagesc(I);
colormap gray
set(ha,'handlevisibility','off', ...
'visible','off');
set(hi,'alphadata',.95);

uibuttongroup('Visible','on',...
    'BackgroundColor',[0.75,0.75,0.75],...
    'ForegroundColor','black',...
    'Title','Valori intrare I',...
    'FontSize',9,...
    'TitlePosition','centertop',...
    'Tag','radiobutton',...
    'Position',[0.46 0.68 0.275 0.3]);

%buton tip text si edit pt A1
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.47 0.89 0.12 0.05],...
 'String','A1 = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.6 0.89 0.12 0.05],...
'String', num2str(A1),...
'Callback', 'A1=str2num(get(gco, ''String''));');

%buton tip text si edit pt R1
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.47 0.83 0.12 0.05],...
 'String','R1 = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.6 0.83 0.12 0.05],...
'String', num2str(R1),...
'Callback', 'R1=str2num(get(gco, ''String''));');

%buton tip text si edit pt f1
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.47 0.77 0.12 0.05],...
 'String','f1 = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.6 0.77 0.12 0.05],...
'String', num2str(F1),...
'Callback', 'F1=str2num(get(gco, ''String''));');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.47 0.71 0.12 0.05],...
 'String','Tip semnal ');

uicontrol('style','popup',...
    'units','normalized',...
    'position',[0.6 0.665 0.12 0.09],...
    'value',tip,...
    'string','DC|SIN|DREPTUNGHIULAR|dinte de Fierastrau',...
    'callback','tip=get(gco,''value'');close;sumator1(tip,tip1,R,R1,R2,A1,A2,F1,F2,N,Vo1,Vo2, DC1, DC2);');

uibuttongroup('Visible','on',...
    'BackgroundColor',[0.75,0.75,0.75],...
    'ForegroundColor','black',...
    'Title','Valori intrare II',...
    'FontSize',9,...
    'TitlePosition','centertop',...
    'Tag','radiobutton',...
    'Position',[0.74 0.68 0.275 0.3]);

%buton tip text si edit pt A2
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.75 0.89 0.12 0.05],...
 'String','A2 = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.88 0.89 0.12 0.05],...
'String', num2str(A2),...
'Callback', 'A2=str2num(get(gco, ''String''));');

%buton tip text si edit pt R1
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.75 0.83 0.12 0.05],...
 'String','R2 = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.88 0.83 0.12 0.05],...
'String', num2str(R2),...
'Callback', 'R2=str2num(get(gco, ''String''));');

%buton tip text si edit pt f2
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.75 0.77 0.12 0.05],...
 'String','f2 = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.88 0.77 0.12 0.05],...
'String', num2str(F2),...
'Callback', 'F2=str2num(get(gco, ''String''));');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.75 0.71 0.12 0.05],...
 'String','Tip semnal ');

uicontrol('style','popup',...
    'units','normalized',...
    'position',[0.88 0.665 0.12 0.09],...
    'value',tip1,...
    'string','DC|SIN|DREPTUNGHIULAR|dinte de Fierastrau',...
    'callback','tip1=get(gco,''value'');close;sumator1(tip,tip1,R,R1,R2,A1,A2,F1,F2,N,Vo1,Vo2,DC1,DC2);');

%buton tip text si edit pt R
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.74 0.57 0.12 0.05],...
 'String','R = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.87 0.57 0.12 0.05],...
'String', num2str(R),...
'Callback', 'R=str2num(get(gco, ''String''));');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.74 0.51 0.12 0.05],...
 'String','Np = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.87 0.51 0.12 0.05],...
'String', num2str(N),...
'Callback', 'N=str2num(get(gco, ''String''));');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.74 0.44 0.12 0.05],...
 'String','Vo1 = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.87 0.44 0.12 0.05],...
'String', num2str(Vo1),...
'Callback', 'Vo1=str2num(get(gco, ''String''));');
    
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.74 0.37 0.12 0.05],...
 'String','Vo2 = ');

uicontrol('Style', 'edit',...
'Units', 'normalized',...
'Position', [0.87 0.37 0.12 0.05],...
'String', num2str(Vo2),...
'Callback', 'Vo2=str2num(get(gco, ''String''));');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.74 0.31 0.12 0.05],...
 'String','DC pt vi1: ');

uicontrol('Style','Checkbox',...
    'Units','normalized',...
    'String','DC',...
    'Position', [0.87 0.31 0.04 0.04],...
    'backgroundcolor', 'black',...
    'foregroundcolor', 'w',...
    'Value', DC1,...
    'Callback','DC1=get(gco, ''Value'')')

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.74 0.24 0.12 0.05],...
 'String','DC pt vi2: ');

uicontrol('Style','Checkbox',...
    'Units','normalized',...
    'String','DC',...
    'Position', [0.87 0.24 0.04 0.04],...
    'backgroundcolor', 'black',...
    'foregroundcolor', 'w',...
    'Value', DC2,...
    'Callback','DC2=get(gco, ''Value'')')

uicontrol('Style','pushbutton',... 
'Units','normalized',...
'Position',[0.8 0.1 0.2 .1],...
'string','Reset',...
'Callback','close;sumator1(tip,tip1,R,R1,R2,A1,A2,F1,F2,N,Vo1,Vo2, DC1, DC2);');

dcSemnal1 = 0;
    if DC1 == 1
        dcSemnal1 = 1;
    end

switch(tip)
    case 1
vi=A1.*ones(1, length(t1));
    case 2
vi=dcSemnal1+A1.*sin(2.*pi.*F1.*t1);
    case 3
vi=dcSemnal1+A1.*square(2.*pi.*F1.*t1);
    case 4
vi=dcSemnal1+A1.*sawtooth(2.*pi.*F1.*t1, 1);
end

dcSemnal2 = 0;
    if DC2 == 1
        dcSemnal2 = 1;
    end
    
switch(tip1)
    case 1
vi1=A2.*ones(1, length(t2));
    case 2
vi1=dcSemnal2+A2.*sin(2.*pi.*F2.*t2);
    case 3
vi1=dcSemnal2+A2.*square(2.*pi.*F2.*t2);
    case 4
vi1=dcSemnal2+A2.*sawtooth(2.*pi.*F2.*t2, 1);
end

vo=-((R*vi/R1)+(R*vi1/R2)); 
for i=1:length(t) 
if vo(i)<Vo2
    vo(i)=Vo2;
elseif vo(i)>Vo1
    vo(i)=Vo1;
end
end
            
axes('position',[0.065,0.36,0.5,0.19]);
plot(t1,vi,'b',t2,vi1,'r');
legend('Vi1','Vi2');
xlabel('Timpul (s)');
grid;
axes('position',[0.065,0.06,0.5,0.19]);
plot(t,vo);
legend('Vo');
xlabel('Timpul (s)');
hold on;
grid;

end